# Use an official Python runtime as the base image
FROM python:3.11

# Set the working directory in the container to /app
WORKDIR /app

# Install Poetry
RUN pip install poetry

# Copy pyproject.toml and poetry.lock to the working directory
COPY ./backend/pyproject.toml ./backend/poetry.lock ./

# Install project dependencies
RUN poetry config virtualenvs.create false && poetry install --no-dev

# Copy the rest of the application to the working directory
COPY ./backend .
ENV VITE_baseURL=""

# Expose port 8000 for the FastAPI server
EXPOSE 8000

# Start the FastAPI server
CMD ["poetry","run","prod"]
